/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

configurations {
    compileOnly {
        extendsFrom(configurations.annotationProcessor.get())
    }
}


dependencies {
    implementation(project(":utilities"))
    implementation("com.konghq:unirest-java-core")
    implementation("com.konghq:unirest-objectmapper-jackson")

    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.kafka:spring-kafka")
    implementation("org.apache.avro:avro")
    implementation("io.confluent:kafka-avro-serializer")
    implementation("com.maxmind.geoip2:geoip2:2.15.0")

    compileOnly("org.projectlombok:lombok")
    annotationProcessor("org.projectlombok:lombok")

}
