/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("buildlogic.migration-conventions")
}


repositories {
    mavenCentral()
}

liquibase {
    activities.create("dev") {
        arguments = mapOf(
            "changelogFile" to "src\\main\\db\\main.xml",
            "url" to "jdbc:postgresql://localhost:15432/cyver-plant",
            "username" to "postgres",
            "password" to "1234",
            "logLevel" to "info",
            "tag" to "dev-002"
        )
    }
    activities.create("h2") {
        arguments = mapOf(
            "changelogFile" to "src\\main\\dbh2\\main.xml",
            "url" to "jdbc:h2:file:./build/h2db/cyver-plant",
            "username" to "sa",
            "password" to "1234",
            "logLevel" to "info",
            "tag" to "dev-002"
        )
    }
    runList = "h2"

}
