/**
 * CyverPlant2.0 REST API
 *
 * Contact: dev@cyver.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EnvironmentalMeasurementDto { 
    temperatureUnit: EnvironmentalMeasurementDto.TemperatureUnitEnum;
    temperature: number;
    humidity: number;
    heatIndex: number;
    light: number;
    soilMoisture: number;
    measuredAt: string;
}
export namespace EnvironmentalMeasurementDto {
    export type TemperatureUnitEnum = 'CELSIUS' | 'FAHRENHEIT';
    export const TemperatureUnitEnum = {
        Celsius: 'CELSIUS' as TemperatureUnitEnum,
        Fahrenheit: 'FAHRENHEIT' as TemperatureUnitEnum
    };
}


