/**
 * CyverPlant2.0 REST API
 *
 * Contact: dev@cyver.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LogoutDto { 
    logoutUrl?: string;
}

