/*
 * This source file was generated by the Gradle 'init' task
 */
package com.cyver.plant.app;

import com.cyver.plant.list.LinkedList;

import static com.cyver.plant.utilities.StringUtils.join;
import static com.cyver.plant.utilities.StringUtils.split;
import static com.cyver.plant.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
