import com.github.gradle.node.npm.task.NpmTask

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-frontend-conventions")
}

node {
    download = false
}

tasks.register("StartApp", NpmTask::class) {
    description = "Para iniciar la aplicacion en modo de prueba."
    group = "FrontendModule"
    args.set(arrayListOf("start"))
}

tasks.register("BuildApp", NpmTask::class) {
  description = "Para construir la aplicacion."
  group = "FrontendModule"
  args.set(arrayListOf("run", "build"))
}

tasks.register("BuildAppProd", NpmTask::class) {
  description = "Para construir la aplicacion para produccion."
  group = "FrontendModule"
  args.set(arrayListOf("run", "build:prod"))
}
