/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    api(project(":database"))
    api(libs.bundles.utils)
    annotationProcessor(libs.bundles.utilsprocessors)
}
