/*
 * This file was generated by the Gradle 'init' task.
 */
import org.jooq.meta.jaxb.*

plugins {
    id("buildlogic.java-library-conventions")
    id("org.jooq.jooq-codegen-gradle") version "3.20.2"
}


dependencies {
    api(project(":commons"))
    api("org.springframework.boot:spring-boot-starter-jooq") {
        exclude(group = "org.jooq", module = "jooq")
    }
    api(libs.bundles.database)
    jooqCodegen(project(":database:custom-jooq"))
    jooqCodegen(libs.bundles.jooqcodegen)
}

jooq {
    configuration {

        // Configure the database connection here
        generator {
            strategy {
                name = "com.cyver.plant.database.customjooq.CyverPlantNameStrategy"
            }
        }
    }
    executions {
        create("postgresql") {
            configuration {
                jdbc {
                    driver = "org.postgresql.Driver"
                    url = "jdbc:postgresql://localhost:15432/cyver-plant"
                    user = "postgres"
                    password = "1234"
                }
                generator {
                    database {
                        name = "org.jooq.meta.postgres.PostgresDatabase"
                        includes = ".*"
                        excludes = "databasechangelog|databasechangeloglock"
                        inputSchema = "public"
                        forcedTypes {
                            forcedType {

                                // Specify the Java type of your custom type. This corresponds to the Converter's <U> type.
                                userType = "com.cyver.plant.commons.shared.TemperatureUnit"

                                // Apply the built in org.jooq.impl.EnumConverter.
                                isEnumConverter = true

                                // A Java regex matching fully-qualified columns, attributes, parameters. Use the pipe to separate several expressions.
                                includeExpression = "^unit$"
                            }
                        }
                    }
                    generate {
                        isRoutines = true
                        isValidationAnnotations = true
                        isIndexes = false
                        isGeneratedAnnotationJooqVersion = true
                        isImmutablePojos = true
                        isPojosAsJavaRecordClasses = true
                        isSerializablePojos = true
                        generatedSerialVersionUID = GeneratedSerialVersionUID.HASH
                        isSpringAnnotations = true
                        isSpringDao = true
                        isDaos = true
                        isConstructorPropertiesAnnotation = true
                        isConstructorPropertiesAnnotationOnPojos = true
                        isConstructorPropertiesAnnotationOnRecords = true
                    }
                    target {
                        packageName = "com.cyver.plant.database"
                    }

                }

            }
        }
        create("h2") {
            configuration {
                generator {
                    database {
                        name = "org.jooq.meta.extensions.ddl.DDLDatabase"
                        java = "org.jooq.meta.h2.H2Database"
                        properties {

                            property {
                                key = "scripts"
                                value = "src/main/resources/dbh2/schema.sql"
                            }

                            property {
                                key = "unqualifiedSchema"
                                value = "none"
                            }

                            property {
                                key = "defaultNameCase"
                                value = "as_is"
                            }
                        }
                        generate {
                            isImmutablePojos = false
                            isSerializablePojos = true
                            generatedSerialVersionUID = GeneratedSerialVersionUID.HASH
                            isSpringAnnotations = true
                            isSpringDao = true
                            isDaos = true
                            isConstructorPropertiesAnnotation = true
                            isConstructorPropertiesAnnotationOnPojos = true
                        }
                        target {
                            packageName = "com.cyver.plant.databaseh2"
                        }
                    }
                }
            }
        }
    }
}

tasks.named("compileJava") {
    dependsOn("jooqCodegen")
}
