/*
 * This file was generated by the Gradle 'init' task.
 */
import org.jooq.meta.jaxb.*

plugins {
    id("buildlogic.java-library-conventions")
    id("org.jooq.jooq-codegen-gradle") version "3.20.2"
}


dependencies {
    api(project(":commons"))
    api("org.springframework.boot:spring-boot-starter-jooq") {
        exclude(group = "org.jooq", module = "jooq")
    }
    api(libs.bundles.database)
    jooqCodegen(project(":database:custom-jooq"))
    jooqCodegen(libs.bundles.jooqcodegen)
}

jooq {
    configuration {

        // Configure the database connection here
        generator {
            strategy {
                name = "com.cyver.plant.database.customjooq.CyverPlantNameStrategy"
            }
        }
    }
    executions {
        create("postgresql") {
            configuration {
                jdbc {
                    driver = "org.postgresql.Driver"
                    url = "jdbc:postgresql://localhost:5432/cyver-plant"
                    user = "postgres"
                    password = "1234"
                }
                generator {
                    database {
                        name = "org.jooq.meta.postgres.PostgresDatabase"
                        includes = ".*"
                        excludes = "databasechangelog|databasechangeloglock"
                        inputSchema = "public"
                        forcedTypes {
                            forcedType {

                                // Specify the Java type of your custom type. This corresponds to the Converter's <U> type.
                                userType = "com.cyver.plant.commons.shared.TemperatureUnit"

                                // Apply the built in org.jooq.impl.EnumConverter.
                                isEnumConverter = true

                                // A Java regex matching fully-qualified columns, attributes, parameters. Use the pipe to separate several expressions.
                                includeExpression = "^unit$"
                            }
                        }
                    }
                    generate {
                        isRoutines = true
                        isValidationAnnotations = true
                        isIndexes = false
                        isGeneratedAnnotationJooqVersion = true
                        isImmutablePojos = true
                        isPojosAsJavaRecordClasses = true
                        isSerializablePojos = true
                        generatedSerialVersionUID = GeneratedSerialVersionUID.HASH
                        isSpringAnnotations = true
                        isSpringDao = true
                        isDaos = true
                        isConstructorPropertiesAnnotation = true
                        isConstructorPropertiesAnnotationOnPojos = true
                        isConstructorPropertiesAnnotationOnRecords = true
                    }
                    target {
                        packageName = "com.cyver.plant.database.cloud"
                    }

                }

            }
        }
        create("h2") {
            configuration {
                generator {
                    database {
                        name = "org.jooq.meta.extensions.liquibase.LiquibaseDatabase"
                        properties {

                            property {
                                key = "rootPath"
                                value = "${project.projectDir}/../migration/src/main/db-h2"
                            }

                            // Specify the classpath location of your XML, YAML, or JSON script.
                            property {
                                key = "scripts"
                                value = "main.xml"
                            }

                            // Whether you want to include liquibase tables in generated output
                            //
                            // - false (default)
                            // - true: includes DATABASECHANGELOG and DATABASECHANGELOGLOCK tables
                            property {
                                key = "includeLiquibaseTables"
                                value = "false"
                            }

                            // Whether you want to use jOOQ's translating ParsingConnection to translate
                            // between your dialect (e.g. Oracle), and jOOQ's in-memory H2 dialect
                            //
                            // - false (default)
                            // - true: translates e.g. from VARCHAR2(100) to VARCHAR(100)
                            property {
                                key = "useParsingConnection"
                                value = "false"
                            }

                            // Properties prefixed "database." will be passed on to the liquibase.database.Database class
                            // if a matching setter is found
                            property {
                                key = "database.liquibaseSchemaName"
                                value = "public"
                            }

                            // The property "changeLogParameters.contexts" will be passed on to the
                            // liquibase.database.Database.update() call (jOOQ 3.13.2+).
                            // See https://www.liquibase.org/documentation/contexts.html
                            property {
                                key = "changeLogParameters.contexts"
                                value = "!test"
                            }
                        }
                        generate {
                            isImmutablePojos = false
                            isSerializablePojos = true
                            generatedSerialVersionUID = GeneratedSerialVersionUID.HASH
                            isSpringAnnotations = true
                            isSpringDao = true
                            isDaos = true
                            isConstructorPropertiesAnnotation = true
                            isConstructorPropertiesAnnotationOnPojos = true
                        }
                        target {
                            packageName = "com.cyver.plant.database.producer"
                        }
                    }
                }
            }
        }
    }
}

tasks.named("compileJava") {
    dependsOn("jooqCodegen")
}
