-- PUBLIC.CONFIGURATION_OF_NODES definition

-- Drop table

-- DROP TABLE PUBLIC.CONFIGURATION_OF_NODES;

CREATE TABLE PUBLIC.CONFIGURATION_OF_NODES
(
    NODE_ID   BIGINT                 NOT NULL AUTO_INCREMENT,
    NODE_NAME CHARACTER VARYING(150) NOT NULL,
    NODE_TYPE CHARACTER VARYING(150) NOT NULL,
    NODE_URL  CHARACTER VARYING(150) NOT NULL,
    NODE_ABLE BOOLEAN DEFAULT 'true' NOT NULL,
    CONSTRAINT NODE_PKEY PRIMARY KEY (NODE_ID)
);
CREATE UNIQUE INDEX NODE_NAME_AND_TYPE_INDEX ON PUBLIC.CONFIGURATION_OF_NODES (NODE_NAME, NODE_TYPE);
CREATE UNIQUE INDEX PRIMARY_KEY_C ON PUBLIC.CONFIGURATION_OF_NODES (NODE_ID);
