/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("buildlogic.java-common-conventions")
    id("org.springframework.boot")
    // Apply the application plugin to add support for building a CLI application in Java.
    java
    id("com.bmuschko.docker-spring-boot-application")
}
