/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("buildlogic.java-common-conventions")
    id("org.liquibase.gradle")
}

repositories {
    mavenCentral()
}

dependencies {
    liquibaseRuntime("com.h2database:h2:2.3.232")
    liquibaseRuntime("org.postgresql:postgresql:42.7.5")
    liquibaseRuntime("org.liquibase:liquibase-core:4.31.1")
    liquibaseRuntime("info.picocli:picocli:4.6.1")
    liquibaseRuntime("javax.xml.bind:jaxb-api:2.3.1")
    liquibaseRuntime("ch.qos.logback:logback-core:1.2.3")
    liquibaseRuntime("ch.qos.logback:logback-classic:1.2.3")
}
