/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven(url = "https://packages.confluent.io/maven")
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        // https://mvnrepository.com/artifact/jakarta.persistence/jakarta.persistence-api
        implementation("jakarta.persistence:jakarta.persistence-api:3.2.0")
        implementation("io.hypersistence:hypersistence-utils-hibernate-63:3.9.2")
        implementation("org.apache.commons:commons-text:1.12.0")
        implementation("org.apache.avro:avro:1.12.0")
        implementation("io.confluent:kafka-avro-serializer:7.8.0")
        implementation("com.google.guava:guava:33.4.0-jre")
        implementation("org.mapstruct:mapstruct:1.6.3")
        annotationProcessor("org.mapstruct:mapstruct-processor:1.6.3")
        annotationProcessor("org.projectlombok:lombok-mapstruct-binding:0.2.0")
    }


}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
