/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
    mavenCentral()
}

val springbootPlugin = "3.4.2"
val springbootManagementVersions = "1.1.7"
val avroPluginVersion = "1.9.1"
val nodePluginVersion = "7.1.0"
val liquibasePluginVersion = "3.0.2"
val liquibaseCoreVersion = "4.31.1"

dependencies {
    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-gradle-plugin
    implementation("org.springframework.boot:spring-boot-gradle-plugin:${springbootPlugin}")
    // https://mvnrepository.com/artifact/io.spring.gradle/dependency-management-plugin
    implementation("io.spring.gradle:dependency-management-plugin:${springbootManagementVersions}")
    // https://mvnrepository.com/artifact/com.github.davidmc24.gradle.plugin/gradle-avro-plugin
    implementation("com.github.davidmc24.gradle.plugin:gradle-avro-plugin:${avroPluginVersion}")
    // https://mvnrepository.com/artifact/com.github.node-gradle.node/com.github.node-gradle.node.gradle.plugin
    implementation("com.github.node-gradle.node:com.github.node-gradle.node.gradle.plugin:${nodePluginVersion}")
    // https://mvnrepository.com/artifact/org.liquibase.gradle/org.liquibase.gradle.gradle.plugin
    implementation("org.liquibase:liquibase-core:${liquibaseCoreVersion}")
    implementation("org.liquibase.gradle:org.liquibase.gradle.gradle.plugin:${liquibasePluginVersion}")
}
