spring:
  application.name: Producer
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      basic.auth:
        credentials.source: USER_INFO
        user.info: ${SR_KEY}:${SR_SECRET}
      schema.registry.url: ${SCHEMA_REGISTRY_URL}
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='${ACC_SERVICE_USERNAME}' password='${ACC_SERVICE_PASSWORD}';
      session.timeout.ms: 45000
    producer:
      client-id: spring-boot-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

plant:
  interval: ${PLANT_INTERVAL}
  user: ${PLANT_USER}
  topic: ${KAFKA_TOPIC}
  nodes:
    - name: "node1"
      type: "carnivora"
      url: "http://192.168.0.13:8080/measurement"
      minSoilMoisture: 60

client.id: "ccloud-springboot-client-a7fad8aa-c867-44b1-9ab0-491c708d4db7"
